language: go

go:
  - 1.6
  - 1.7
  - tip

install:
  - gobuilder version -c ">=0.1.4" &>/dev/null || go get -u -v "github.com/tsaikd/gobuilder"

script:
  - gobuilder checkfmt
  - gobuilder restore
  - gobuilder get --test --all
  - gobuilder build
  - gobuilder checkerror
  - gobuilder checkredundant
  - go test -v ./cmd/... ./config/... ./filter/...
