language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - gobuilder version -c ">=0.1.3" &>/dev/null || go get -u -v "github.com/tsaikd/gobuilder"

script:
  - gobuilder checkerror
  - gobuilder checkfmt
  - gobuilder restore
  - gobuilder get --test --all
  - gobuilder build
  - go test -v ./cmd/... ./config/... ./filter/...
